name: Playwright Tests

on:
  schedule:
    #Run schedule at 8.10 am CST
    - cron: '10 14 * * *'
  #push:
    #branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - uses: actions/checkout@v4

    # 2. Setup Node
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    # 3. Install dependencies
    - name: Install dependencies
      run: npm ci

    # 4. Install Playwright browsers
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # 5. Run UI + API tests
    - name: Run Playwright Tests
      run: npx playwright test
      continue-on-error: true   # ensures reports generate even if tests fail

    # 6. Upload Playwright HTML Report
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    # 7. Upload Test Results (important for debugging)
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results/

    # 8. Upload Screenshots (your framework)
    - name: Upload Screenshots
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: screenshots
        path: src/screenshots/

    # 9. Upload Winston Logs
    - name: Upload Logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: logs
        path: logs/

    # 10. Install Allure CLI
    - name: Install Allure
      run: npm install -g allure-commandline --save-dev

    # 11. Generate Allure Report
    - name: Generate Allure Report
      run: allure generate ./allure-results --clean -o allure-report

    # 12. Upload Allure Report
    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-report
        path: allure-report/